behaviors:
  Foosbots_MultiRod_5:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 51200
      learning_rate: 5.0e-3
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 500
    summary_freq: 10000
    self_play:
        window: 10
        play_against_latest_model_ratio: 0.5
        save_steps: 20000
        swap_steps: 20000
        team_change: 100000